""" cgi_2.py script """

#!/usr/bin/env python
import os
import datetime

import cgi
import cgitb
cgitb.enable()


DEFAULT = "No Value Present"


print("Content-Type: text/html")
print("")

BODY = """<html>
<head>
<title>Lab 1 - CGI experiments</title>
</head>
<body>
<p>Hey there, this page has been generated by {software}, running {script}</p>
<p>Today is {month} {date}, {year}.</p>
<p>This page was requested by IP Address {client_ip}</p>
</body>
</html>""".format(
    software=os.environ.get('SERVER_SOFTWARE', DEFAULT),
    # script='aaaa',
    # month='bbbb',
    # date='cccc',
    # year='dddd',
    # client_ip='eeee'
    script=os.environ.get('SCRIPT_NAME', DEFAULT),
    month=datetime.datetime.now().strftime('%B'),
    date=datetime.datetime.now().day,
    year=datetime.datetime.now().year,
    client_ip=os.environ.get('REMOTE_ADDR', DEFAULT),
)
print(BODY)
